---
title: "Benjamin From a Distance: Taking a Stroll Down *One-Way Street*"
author: "Jared Jameson"
date: "2023-04-29"
output: html_document
---

## Introduction: Locating Benjamin

Walter Benjamin's book of aphorisms *One-Way Street* was one of two titles that he published in 1928, and those works stand today as the only two book-length projects Benjamin published during his short lifetime. The other 1928 publication, *The Origin of German Tragic Drama*, was Benjamin's failed habilitation, the equivalent of a dissertation for a PhD student in contemporary American education, which was originally intended to win him a position as a professional academic at the much vaunted Goethe University Frankfurt in Germany. To have it rejected, then, brought Benjamin's hopes for a career in academia to a screeching halt. However, despite his habilitation's failure in the eyes of the Frankfurt School's gatekeepers, as his first book, *Origins* shines as one of Benjamin's most commented on works, one considered requisite for any serious understanding of Benjamin's writing, one that has been the subject of in-depth analysis and interpretation far more so than its estranged counterpart *One-Way Street*. This is ironic in that the rejection of *Origins* by his intellectual peers served for Benjamin as a turning point where he would reinvent his style and theoretical bent with a much more radical flare, and *One-Way Street* was to be the book that announced this change in artistic direction. 

Benjamin's new artistic mode wasn't exactly ready-made for a widespread audience, though, as *One-Way Street* has often been viewed as a largely inaccessible, obtuse, and cryptic text that defies attempts at interpreting the sum of the various adjacent blocks of script printed on each page as a cohesive and uniform whole with connected and prescient themes. Benjamin scholar James McFarland, for example, writing in 2012 notes *One-Way Street* as "an avant-garde experiment involving sixty fragmentary and unorthodox texts, including everything from satirical lists to dreamprotocols to descriptions of children’s behavior, One-Way Street resists comprehension and so its exposition has languished."^1^ Though books of aphorisms were fairly common in the 20s when *One-Way Street* was published,^2^ Benjamin's esoteric, theoretical, and philosophical bents all seemed to permeate his writing in such a way that continually mystifies his reader to this day. 

*One-Way Street* is a radical book. One dedicated to, as the epigraph written on the books opening page plainly states, "Asja Lacis Street / after her who / as an engineer / cut it through the author."^3^ From the start, Benjamin poses *One-Way Street* not only as a collaborative effort by naming Lacis as its original architect but also as a monument to his intimate experience with a woman who so greatly impacted his life as to completely reconfigure the inner-most terrain of his identity. This clearly hints at the somewhat auto-biographical nature of the book, and perhaps offers a clue as to how the writing should be interpreted. It is no coincidence that Asja Lacis was also a Bolshevik communist that spurned an interest in communist ideology in Benjamin at a formative moment in his life. And Benjamin made it relatively clear in his writing that his interest in Lacis related directly to her politics. As McFarland puts it, "Benjamin considered his meeting with Asja Lacis to make epoch in his own existence, and his assessment of her significance . . . says nothing of her beauty but emphasizes her political character."^4^ The political nature of Benjamin's relationship to the woman he dedicated the book to strongly implies that the text of *One-Way Street* is politically charged and intended, in some ways, to function rhetorically as a type of propaganda for Benjamin's new found cause. Analyzing *One-Way Street* from this perspective, then, may also shed light on the historical moment that Benjamin inhabited. 

Previously, critical methodologies have lacked certain tools that might facilitate such a recontextualization, and in a digital era where maps, textual structures, and social networks can easily be visualized in new ways, the opportunity for a distant reading of Benjamin offers a new pathway to interpreting this text that has been so legendarily uninterpretable. These tools enable scholars to answer the call for radical new ways of "reading," since, as McFarland says, *One-Way Street* demands "readings  as  intrepid  as  its own  radical  posture."^5^ Specifically, the power of statistical analysis, which opens up the text to quantitative analysis, combined with the R programming language, which enables the plotting and visualizations of compiled data in various graphical forms, creates the opportunity to subject Benjamin's enigmatic *One-Way Street* to a round of textual analysis with the hopes that a distant reading of the text might produce new insights that can in turn lead to new or more robust interpretations of the book. **More precisely, the question driving this project is: How can programming languages like R, when employed as a tool for textual analysis, improve the experience of reading complicated texts like *One-Way Street* and lead to more satisfying and meaningful interpretations?** 

## Methodologies and Techniques: Using R to Mine Benjamin's sCrypt

To start this analysis of *One-Way Street*, the first step was to create the dataset, or the corpus, to be analyzed. This entailed, for one, the transcribing of *One-Way Street* into plain text files, one text file for each individual passage in the book. This was accomplished by first acquiring a digital .PDF version of the text, in this case the Edmund Jephcott and Kingsley Shorter translation from their collection *One-Way Street and Other Writings*.^6^ Then Adobe Acrobat was used to run optical character recognition (OCR), which started the process by making the text selectable and thereby transferrable into a plain text editor, in this case Note ++ was used to create the .txt files to make up the corpus. After OCR was completed, the text for the PDF was transferred over to a single text file, where the text was reviewed for any errors in the OCR process, of which there were many. Once these errors were corrected and the text accurately reflected the source material, the individual passages were copied into new text files and each saved individually with nothing but the text of the file, meaning the title was not included as part of the passage itself (although titles were recorded in the metadata file. More on that later). These files were all saved into a directory titled "OWS-Benjamin." In total there were sixty-two files, including sixty individual passages; one file for the introductory epigraph that serves as the books dedication; and one file for the complete work, unseperated and titled. 


With the .txt files created, it was time to create the metadata file. This file consist of a spreadsheet, containing all of the relevant metadata that would be associated with each individual passage. This is where information about the title, the year written, or the structural type is listed to supplement the interpretations produced later in the analysis. This file also serves to store all of the later results from counts and other analytical techniques that will be the building blocks for this projects final conclusions. 
 




## End Notes

1. McFarland, “Setting the Stage," 212.

2. Scholem cited in a footnote in Sontag, Introduction, 19. 

3. Benjamin, *One-Way Street*, 45.

4. McFarland, "Setting the Stage," 214.

5. McFarland, "Setting the Stage," 215.

6. This version was first published in 1978 as the first English traslation of the full cycle of writing that made up the original German version, *Einbahnstraße*. Benjamin, Walter. *One-Way Street*.





## Bibliography

Benjamin, Walter. *One-Way Street*. *One-Way Street and Other Writings*, trans. Edmund Jephcott and Kingsley Shorter. NLB, 1979.

Benjamin, Walter. *The Origins of German Tragic Drama*. Verso, 1998.

McFarland, James. “Setting the Stage: An Introduction to One-Way Street.” In The Germanic Review: Literature, Culture, Theory, 87, no. 3, (2012): 211-216. DOI: 10.1080/00168890.2012.707939.

Sontag, Susan. Introduction. In *One-Way Street and Other Writings*, trans. Edmund Jephcott and Kingsley Shorter. NLB, 1979.